version: '3.8'

services:
  php:
    build: .
    ports:
      - "8080:80"  # Changed port to 8080
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
    networks:
      - my-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: outfitadmin123
      MYSQL_DATABASE: outfitt
    volumes:
      - ./outfitt.sql:/docker-entrypoint-initdb.d/outfitt.sql  # Mount the SQL dump file
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
